name: Deploy static site
on: { push: { branches: [main] } }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH (rsync)
        uses: easingthemes/ssh-deploy@v5
        with:
          REMOTE_HOST: ${{ secrets.H_HOST }}
          REMOTE_USER: ${{ secrets.H_USER }}
          REMOTE_PORT: 65002
          SSH_PRIVATE_KEY: ${{ secrets.H_SSH_KEY }}
          SOURCE: .
          TARGET: ${{ secrets.H_PATH }}
          ARGS: "-rlgoDzvc --delete"
          EXCLUDE: ".git/, .github/"
          REMOTE_CMD: "mkdir -p ${{ secrets.H_PATH }}"
