name: Deploy static site
on: { push: { branches: [main] } }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host:     ${{ secrets.H_HOST }}
          username: ${{ secrets.H_USER }}
          port:     65002
          key:      ${{ secrets.H_SSH_KEY }}
          source:   "."
          target:   ${{ secrets.H_PATH }}
          overwrite: true
          rm: true
          strip_components: 0
          exclude: |
            .git/*
            .github/*

      - name: Fix permissions (optional)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.H_HOST }}
          username: ${{ secrets.H_USER }}
          port:     65002
          key:      ${{ secrets.H_SSH_KEY }}
          script: |
            chmod -R u+rwX,go+rX ${{ secrets.H_PATH }}